### ISSUE TITLE
Projectionist broken with loop

### ISSUE THREAD

**Issue by algrym** [algrym/projectionist#2]
Feb 12 03:18:07 urania.7344.toxaway.us systemd[457]: Started Projectionist MQTT-to-Serial projector control service.
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: publish availability topic="projectionist/urania.7344.toxaway.us/tk850/LWT" available=True
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: publishQ worker: qsize=3 topic="projectionist/urania.7344.toxaway.us/tk850/LWT" payload="Online" retain="False"
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: mqtt disconnect userdata="None" rc=7
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serialQ worker: qsize=3 msg="b'\r*ltim=?#\r'"
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: worker updates queued. Sleeping for 600 secs
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial echo back: '>*modelname=?#'
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial found MODELNAME=TK850i
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]: Exception in thread Thread-4:
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]: Traceback (most recent call last):
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:     self.run()
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:   File "/usr/lib/python3.7/threading.py", line 865, in run
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:     self._target(*self._args, **self._kwargs)
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:   File "/home/ajw/projectionist/projectionist.py", line 343, in publishq_worker
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:     f"publishQ worker failed mid={result.mid} rc={result.rc} result.is_published()={result.is_published()}"
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:   File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 381, in is_published
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]:     raise RuntimeError('Message publish failed: %s' % (error_string(self.rc)))
Feb 12 03:18:07 urania.7344.toxaway.us projectionist.py[1322]: RuntimeError: Message publish failed: The client is not currently connected.
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serialQ worker: qsize=2 msg="b'\r*pow=?#\r'"
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial echo back: '>*ltim=?#'
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial found LTIM=2212
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial echo back: '>*pow=?#'
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial found POW=OFF
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serialQ worker: qsize=1 msg="b'\r*sour=?#\r'"
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial echo back: '>*sour=?#'
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial found SOUR=RGB
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serialQ worker: qsize=0 msg="b'\r*blank=?#\r'"
Feb 12 03:18:07 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial echo back: '>*blank=?#'
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: serial found BLANK=OFF
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k120) client_id=b'urania.7344.toxaway.us'
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Received CONNACK (0, 0)
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: MQTT connect flags="{'session present': 0}", result code=0
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Sending SUBSCRIBE (d0, m5) [(b'projectionist/urania.7344.toxaway.us/tk850/power/set', 0)]
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Sending SUBSCRIBE (d0, m6) [(b'projectionist/urania.7344.toxaway.us/tk850/source/set', 0)]
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Sending SUBSCRIBE (d0, m7) [(b'projectionist/urania.7344.toxaway.us/tk850/blank/set', 0)]
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: publish availability topic="projectionist/urania.7344.toxaway.us/tk850/LWT" available=True
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Received SUBACK
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Received SUBACK
Feb 12 03:18:08 urania.7344.toxaway.us /home/ajw/projectionist/projectionist.py[1322]: Received SUBACK

**Comment by algrym** [comment]
Maybe? https://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages/

**Comment by algrym** [comment]
Mea culpa.  

MQTT uses "client-id" to determine if there is an existing connection.

Starting a second connection to the MQTT broker with the same client-id (even if its from another software package) will cause woes.

Closed: pilot error on my part.
